### PR TITLE
Add sample application to demonstrate secure messaging with Node.js using NodeX Agent

### PR DESCRIPTION
**Pull request by KeisukeYamashita**
## Why 

To help users onboard to create their applications.
This example application will show how the data are sent and received, how they can build an app using NodeX Agent, etc.

### CODE REVIEW

**Review by miseyu — COMMENTED** [review]
> Question

Do you expect us to use both `src` and `app` as examples, without deleting the sources in `examples/nodejs/src`?

**Comment by KeisukeYamashita** [comment]
> > Question
> 
> @KeisukeYamashita Do you expect us to use both `src` and `app` as examples, without deleting the sources in `examples/nodejs/src`?

I expect both!
I understand that it is bit awkward, but the exising CLI like code is used everywhere (for example, the NodeX documentation ). Let me rename the existing one!

**Review by miseyu — APPROVED** [review]
Thank you!
LGTM!!

**Comment by KeisukeYamashita** [comment]
> > > Question
> > 
> > 
> > @KeisukeYamashita Do you expect us to use both `src` and `app` as examples, without deleting the sources in `examples/nodejs/src`?
> 
> I expect both! I understand that it is bit awkward, but the exising CLI like code is used everywhere (for example, the NodeX documentation )! Let me rename it!

@miseyu  I have update to use the `cli/` directory for the existing `src/`. This will not affect any existing user or documentation as we can still `yarn <command in cli/>` 👍  No breaking change 👉　https://github.com/nodecross/nodex/pull/198/commits/05f2abd5142e4bfec91d0885293750c6ed8ee4e5

Also, I fixed a typo 🙏 https://github.com/nodecross/nodex/pull/198/commits/4a9a54e2db6f64fca563b80cbcda1505f0c41511
PTAL when you got a chance!

**Review by miseyu — APPROVED** [review]
Thank you very much!
LGTM!!

**Comment by KeisukeYamashita** [comment]
Sorry, one more thing 🙏  https://github.com/nodecross/nodex/pull/198/commits/59a7e5dd88427cd8e8f48e17c21d306e349e3c57
I found a typo which I forgot to push because of the commit hook failure 🙏 🐗

**Review by miseyu — APPROVED** [review]
I understood!
LGTM!!

**Comment by KeisukeYamashita** [comment]
Thank you, sorry for the bothering 😢 
I'll merge this 💪

**Pull request merged**
